from __future__ import annotations
import io, json, zipfile, re
from typing import Any, Dict
from fastapi import FastAPI, APIRouter, Request, HTTPException
from fastapi.responses import JSONResponse
from .common import require_admin
from .engines import _store_artifact  # type: ignore

def _sanitize(name: str) -> str:
    name = (name or "atlas_product").strip().lower()
    name = re.sub(r"[^a-z0-9_\-]+","_", name)[:48].strip("_")
    return name or "atlas_product"

def _dockerfile_fastapi() -> str:
    return """# syntax=docker/dockerfile:1
FROM python:3.11-slim AS runtime
WORKDIR /app
COPY backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY backend /app/backend
ENV PORT=8000
CMD [\"python\", \"-m\", \"uvicorn\", \"backend.app.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]
"""

def _render_yaml(service_name: str) -> str:
    return f"""services:
- type: web
  name: {service_name}
  env: python
  buildCommand: pip install -r backend/requirements.txt
  startCommand: python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
  envVars:
  - key: ATLAS_DB_PATH
    value: /var/data/app.db
"""

def _gha_ci() -> str:
    return """name: ci
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -r backend/requirements.txt
      - run: python -c "from backend.app.main import app; print('ok')"
"""

def _gen_zip(spec: Dict[str, Any]) -> bytes:
    name = _sanitize(str(spec.get("name") or "atlas_product"))
    kind = str(spec.get("kind") or "app")  # app|plugin
    stack = str(spec.get("stack") or "fastapi+react")
    target = str(spec.get("target") or "render")

    readme = f"""# {name}
Generated by Atlas Builder v2

- kind: {kind}
- stack: {stack}
- target: {target}

## Run
Backend:
python -m venv .venv && . .venv/bin/activate
pip install -r backend/requirements.txt
python -m uvicorn backend.app.main:app --reload --port 8000

Frontend:
cd frontend
npm install
npm run dev
"""

    backend_main = """from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="Product API")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

@app.get("/healthz")
def healthz():
    return {"ok": True}
"""

    plugin_router = """from fastapi import APIRouter
router = APIRouter(prefix="/api/plugins/{name}", tags=["plugins"])
@router.get("/ping")
def ping():
    return {"ok": True, "plugin": "{name}"}
""".replace("{name}", name)

    package_json = {
      "name": name,
      "private": True,
      "version": "0.1.0",
      "type": "module",
      "scripts": {"dev":"vite","build":"vite build","preview":"vite preview"},
      "dependencies": {"react":"^18.2.0","react-dom":"^18.2.0"},
      "devDependencies": {"vite":"^5.4.0","typescript":"^5.5.0","@types/react":"^18.2.0","@types/react-dom":"^18.2.0"}
    }
    requirements = "fastapi>=0.111.0\nuvicorn[standard]>=0.30.0\n"

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.writestr(f"{name}/README.md", readme)
        z.writestr(f"{name}/Dockerfile", _dockerfile_fastapi())
        z.writestr(f"{name}/render.yaml", _render_yaml(name))
        z.writestr(f"{name}/.github/workflows/ci.yml", _gha_ci())
        z.writestr(f"{name}/backend/app/main.py", backend_main)
        z.writestr(f"{name}/backend/requirements.txt", requirements)
        if kind == "plugin":
            z.writestr(f"{name}/backend/plugin_router.py", plugin_router)
            z.writestr(f"{name}/manifest.json", json.dumps({"id":name,"name":name,"version":"0.1.0","description":"Generated plugin"}, indent=2))
        z.writestr(f"{name}/frontend/src/main.tsx", "import React from 'react'\nimport ReactDOM from 'react-dom/client'\nfunction App(){return <div>Hello {name}</div>}\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)\n".replace("{name}", name))
        z.writestr(f"{name}/frontend/package.json", json.dumps(package_json, indent=2))
        z.writestr(f"{name}/frontend/index.html", "<!doctype html><html><body><div id='root'></div><script type='module' src='/src/main.tsx'></script></body></html>")
    return buf.getvalue()

def install_builder_v2(app: FastAPI) -> None:
    r = APIRouter(prefix="/api/builder", tags=["builder"])
    @r.post("/generate-zip")
    async def generate(request: Request, payload: Dict[str, Any]):
        try:
            require_admin(dict(request.headers))
        except PermissionError as e:
            raise HTTPException(status_code=401, detail=str(e))
        spec = payload.get("spec") or {}
        content = _gen_zip(spec)
        artifact = _store_artifact("builder_zip", "builder_output.zip", content, {"spec": spec})
        return {"ok": True, "artifact": artifact}
    app.include_router(r)
